---
- hosts: shards
  become: true
  vars:
    container_count: 2
    default_container_name: secondary-mongo-
    default_container_image: mongo
    default_container_command: sleep 1d

  tasks:
    - name: Pull default container image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create primary node container
      community.docker.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image}}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ container_count }}i
